backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "/public/assets/images"
public_folder: "/assets/images"
collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "projects" # Used in the UI
    folder: "src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "title", name: "title", widget: "string" }
      - { label: "tag", name: "tag", widget: "list", default: ["Front End"] }
      - { label: "tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "img", name: "img", widget: "image" }
      - { label: "link", name: "link", widget: "string" }
  - name: "about" # Used in routes, e.g., /admin/collections/blog
    label: "about" # Used in the UI
    folder: "src/about" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "h2", name: "h2", widget: "string" }
      - { label: "h3", name: "h3", widget: "string" }
      - { label: "content", name: "content", widget: "code" }
      - { label: "h2Ar", name: "h2Ar", widget: "string" }
      - { label: "h3Ar", name: "h3Ar", widget: "string" }
      - { label: "contentAr", name: "contentAr", widget: "code" }
